AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ArtogradApiS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: artograd-api-s3-bucket
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: Name
          Value: Artograd-API-S3-Bucket

  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: ArtogradApiSpringBootLambda
      Handler: com.artograd.aip.MyHandler::handleRequest
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      Code:
        S3Bucket: Artograd-API-S3-Bucket
        S3Key: artograd-api.jar

  MyLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
Outputs:
  S3BucketName:
    Value: !Ref ArtogradApiS3Bucket
    Description: "Name of the S3 bucket for storing Spring Boot JAR files"