AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaExecutionRole:
    Type: String
    Default: LambdaExecutionRole.Arn
    Description: The name of the IAM role for ECS Task Execution

Resources:
  ArtogradApiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: artograd-api-s3-bucket
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: Name
          Value: Artograd-API-S3-Bucket

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ArtogradApiSpringBootLambda
      Handler: com.artograd.aip.MyHandler::handleRequest
      Role: !ImportValue LambdaExecutionRoleArn
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      Code:
        S3Bucket: !Ref ArtogradApiS3Bucket
#        S3Key: artograd-api.jar

Outputs:
  S3BucketName:
    Value: !Ref ArtogradApiS3Bucket
    Description: "Name of the S3 bucket for storing Spring Boot JAR files"
#  LambdaExecutionRole:
#    Description: The Lambda execution role
#    Value: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${LambdaExecutionRole}'
#    Export:
#      Name: !Sub ${EnvironmentName}:LambdaExecutionRole